name: Haskell CI

on:
  push:
    branches: ["development"]
  pull_request:
    branches: ["development"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-haskell@v1
        with:
          ghc-version: "9.12.2"
          cabal-version: "3.14.2.0"

      - name: Cache
        uses: actions/cache@v3
        env:
          cache-name: cache-cabal
        with:
          path: ~/.cabal
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: |
          cabal update
          cabal build --only-dependencies --enable-tests --enable-benchmarks
      - name: Build
        run: cabal build --enable-tests --enable-benchmarks all
      - name: Run tests
        run: cabal test all
      - name: Generate HTML
        run: |
          mkdir -p site
          cabal run uhoi -- gen-html > site/index.html
      - name: Deploy to GitHub Pages
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git fetch origin
          git checkout --orphan gh-pages
          git reset --hard
          cp -r site/* .
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push --force origin gh-pages
